### ISSUE TITLE
Looks great, but can't be required via composer

### ISSUE THREAD

**Issue by ikethepike** [adam-paterson/watson-tone-analyzer#1]
Looks great, but both this and the ibm-watson-sdk returns:
[InvalidArgumentException]
composer require php-http/curl-client guzzlehttp/psr7 php-http/message adam-paterson/ibm-watson-sdk

after trying to require it.

Thanks!

**Comment by adam-paterson** [comment]
Hi @ikethepike,

Thanks for your interest in library. I never expected their to be any interest at the moment and rewrote the majority of the framework to abstract things out a little more.

I'll double check where I got to with it this evening and if it's in a useable state I'll push it up and update Packagist.

Out of interest, what are you looking to use the lib for?

**Comment by ikethepike** [comment]
We're working on a project with a charity to try to find how friendly the level of discourse is on twitter between world leaders. Right now I'm using the node sdk, but it could streamline things if there was a robust php wrapper and I liked the structure and syntax of yours.
